CREATE TABLE "User" (
	"Userid"	INTEGER NOT NULL UNIQUE,
	"Name"		TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	"UserImage" BLOB NOT NULL,
	PRIMARY KEY("Userid" AUTOINCREMENT)
);